from SCons.Script import ARGUMENTS

Import('globalEnv')

globalEnv.configReport.add('Target platform', 'target_platform')

envArchive = globalEnv.Clone()

files = {}
for t in globalEnv.targetManager.targets.values():
	try:
		files.update(t.archive)
	except:
		pass

targetArchive = globalEnv.targetManager.TargetArchive('DragonScript Archive')
globalEnv.targetManager.add('archive', targetArchive)

if envArchive['archive_format'] == 'tarbz2':
	archiveMethod = targetArchive.formatTarBz2
elif envArchive['archive_format'] == 'zip':
	archiveMethod = targetArchive.formatZip
else:
	raise 'Invalid format {}'.format(envArchive['archive_format'])

targetArchive.archiveFiles(envArchive, envArchive['archive_name_library'], files, archiveMethod)

targetArchive.alias(envArchive, 'archive')
